export const cities = [
  {
    slug: 'istanbul',
    name: 'İstanbul',
    country: 'Türkiye',
    coordinates: [41.0082, 28.9784],
    mood: 'Boğaz mavisi ve doğu-batı köprüsü',
    summary: 'Boğazı vapurla geçin, tarihi yarımadayı yürüyün ve günü Kadıköy çarşısında bitirin.',
    duration: '4-5 gün',
    budget: 'Hesaplı',
    season: 'Bahar ve güz',
    filters: ['budget', 'warm'],
    image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1000&q=80',
    imageAlt: 'İstanbul Boğazı ve tarihi yarımada',
    caption: 'Karaköy ve tarihi yarımada hattı',
    highlights: {
      see: ['Ayasofya, Sultanahmet ve Topkapı', 'Yerebatan Sarnıcı ve Süleymaniye', 'Balat, Fener ve Kuzguncuk'],
      eat: ['Eminönü balık ekmek', 'Kadıköy Çarşısı sokak lezzetleri', 'Çiya Sofrası geleneksel mutfak'],
      do: ['Gün batımında Şehir Hatları vapuru', 'Kılıç Ali Paşa Hamamı', 'Çukurcuma antikacıları'],
    },
    stays: ['Tarihi odak: Sultanahmet ve Sirkeci.', 'Dinamik akşamlar: Karaköy ve Galata.', 'Daha yerel ve sakin: Moda, Kadıköy.'],
    transport: ['İstanbul Havalimanı: M11 metrosu veya Havaist servisleri.', 'Sabiha Gökçen: M4 ile Kadıköy yönü.', 'Şehir içi: İstanbulkart ile vapur ve Marmaray kullanın.'],
    notes: ['Turistik caddelerde taksi yerine raylı sistemi veya araç çağırmayı tercih edin.', 'Kapalıçarşı ve Mısır Çarşısı alışverişinde fiyatları karşılaştırın.'],
  },
  {
    slug: 'londra',
    name: 'Londra',
    country: 'Birleşik Krallık',
    coordinates: [51.5072, -0.1276],
    mood: 'Kraliyet kırmızısı ve Viktorya dokusu',
    summary: 'Ücretsiz müzelerden başlayıp Thames boyunca yürüyün, akşamı West End sahnelerinde geçirin.',
    duration: '4-6 gün',
    budget: 'Yüksek',
    season: 'Mayıs-Eylül',
    filters: ['classic'],
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1000&q=80',
    imageAlt: 'Londra sokakları ve Westminster silüeti',
    caption: 'Big Ben ve Westminster çevresi',
    highlights: {
      see: ['British Museum ve V&A', 'Tower Bridge ve Londra Kalesi', 'Hyde Park ve Buckingham Sarayı'],
      eat: ['Borough Market sokak lezzetleri', 'Poppies fish and chips', 'Mayfair’de ikindi çayı'],
      do: ['West End’de müzikal', 'Camden Town pazarı', 'Sky Garden şehir manzarası'],
    },
    stays: ['Merkezi ve tiyatroya yakın: Soho ve Covent Garden.', 'Müzelere yakın: South Kensington.', 'Bohem ve vintage: Shoreditch.'],
    transport: ['Heathrow: Elizabeth Line veya Piccadilly metro hattı genellikle ekspres trenden daha ekonomik olur.', 'Şehir içi: Temassız kartla turnikelerde giriş ve çıkış yapın.'],
    notes: ['Sky Garden için ücretsiz giriş saatleri hızla dolabilir; önceden kontrol edin.', 'West End için Leicester Square’deki TKTS noktasında aynı gün fırsatlarını sorun.'],
  },
  {
    slug: 'berlin',
    name: 'Berlin',
    country: 'Almanya',
    coordinates: [52.52, 13.405],
    mood: 'Mat endüstriyel gri ve yeraltı sanatı',
    summary: 'Duvar izlerini, büyük parkları ve bağımsız gece hayatını aynı rotada görün.',
    duration: '3-4 gün',
    budget: 'Orta-hesaplı',
    season: 'Mayıs-Ekim',
    filters: ['budget'],
    image: 'https://images.unsplash.com/photo-1560969184-10fe8719e047?auto=format&fit=crop&w=1000&q=80',
    imageAlt: 'Berlin Katedrali ve Spree kanalı',
    caption: 'Berlin Katedrali ve Spree kanalı',
    highlights: {
      see: ['East Side Gallery', 'Reichstag cam kubbesi ve Brandenburg Kapısı', 'Müzeler Adası'],
      eat: ['Curry 36 körili sosis', 'Mustafa’s Gemüse Döner', 'Markthalle Neun'],
      do: ['Tempelhofer Feld’de paten', 'Mauerpark açık hava karaokesi', 'Friedrichshain kulüpleri'],
    },
    stays: ['Merkezi ve düzenli: Mitte.', 'Bohem ve butik: Prenzlauer Berg.', 'Gece hayatı ve sanat: Friedrichshain veya Kreuzberg.'],
    transport: ['BER Havalimanı: Güncel bağlantı ve hareket saatini VBB’nin resmi yolculuk planlayıcısından kontrol edin.', 'Bilet uyarısı: Turnikesiz istasyonlarda biletinizi perondaki cihazda damgalayın.'],
    notes: ['Reichstag kubbesi için giriş şartlarını ve rezervasyonu resmi kaynaktan kontrol edin.', 'Kulüp kapılarında gösterişsiz giyinmek ve sırada sakin kalmak yaygın beklentidir.'],
  },
  {
    slug: 'madrid',
    name: 'Madrid',
    country: 'İspanya',
    coordinates: [40.4168, -3.7038],
    mood: 'Kehribar sarısı ve kraliyet meydanları',
    summary: 'Prado ile başlayın, Retiro’da soluklanın ve tapas barlarının dolduğu geç saatlere hazırlıklı olun.',
    duration: '3-4 gün',
    budget: 'Orta',
    season: 'Bahar ve sonbahar',
    filters: ['warm'],
    image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1000&q=80',
    imageAlt: 'Madrid Gran Vía caddesi',
    caption: 'Gran Vía ve Metropolis',
    highlights: {
      see: ['Prado ve Reina Sofía', 'Madrid Kraliyet Sarayı', 'El Retiro Parkı ve Kristal Saray'],
      eat: ['San Ginés churros', 'Mercado de San Miguel tapasları', 'Plaza Mayor kalamar ekmeği'],
      do: ['Debod Tapınağı’nda gün batımı', 'El Rastro pazarı', 'Flamenko gösterisi'],
    },
    stays: ['Her yere yürümek için: Sol ve Gran Vía.', 'Tarih ve edebiyat için: Barrio de Las Letras.', 'Genç ve hareketli: Malasaña ve Chueca.'],
    transport: ['Barajas: 8 numaralı metro hattı veya Exprés Aeropuerto otobüsü.', 'Şehir içi: Çoklu biniş kartları otobüs ve metroda kullanılabilir.'],
    notes: ['Prado’nun ücretsiz giriş pencereleri değişebilir; resmi saatleri kontrol edin.', 'Akşam yemeği geç başlar; öğleden sonra bazı küçük işletmeler kapalı olabilir.'],
  },
  {
    slug: 'viyana',
    name: 'Viyana',
    country: 'Avusturya',
    coordinates: [48.2082, 16.3738],
    mood: 'Habsburg saray altını ve klasik müzik',
    summary: 'Sarayları ve müzeleri gezdikten sonra bir kahve evinde yavaşlayın, akşamı operayla tamamlayın.',
    duration: '3 gün',
    budget: 'Orta-yüksek',
    season: 'Mayıs ve aralık',
    filters: ['classic'],
    image: 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?auto=format&fit=crop&w=1000&q=80',
    imageAlt: 'Viyana’daki tarihi saray mimarisi',
    caption: 'Hofburg Sarayı meydanı',
    highlights: {
      see: ['Schönbrunn ve Hofburg sarayları', 'Belvedere Müzesi', 'Aziz Stephan Katedrali'],
      eat: ['Figlmüller schnitzel', 'Hotel Sacher’de Sachertorte', 'Melange ve Apfelstrudel'],
      do: ['Operada ayakta bilet', 'Prater dönme dolabı', 'Grinzing bağ evleri'],
    },
    stays: ['Tarihi merkez: Innere Stadt.', 'Sanat ve kafeler: Neubau.', 'Geniş ve rahat sokaklar: Leopoldstadt.'],
    transport: ['Schwechat: S7 banliyö treni, ekspres trene ekonomik bir alternatiftir.', 'Şehir içi: Seyahatinize uygun güncel bilet türü ve ücretini Wiener Linien’den kontrol edin.'],
    notes: ['Devlet Operası ayakta izleme biletlerinin satış koşullarını aynı gün kontrol edin.', 'Pazar günü süpermarketler dahil birçok işletme kapalı olur.'],
  },
  {
    slug: 'budapeste',
    name: 'Budapeşte',
    country: 'Macaristan',
    coordinates: [47.4979, 19.0402],
    mood: 'Tuna yeşili ve termal kültür',
    summary: 'Tuna kıyısındaki Parlamento’yu görün, termalde dinlenin ve akşamı harap barlarda geçirin.',
    duration: '3 gün',
    budget: 'Çok hesaplı',
    season: 'Mayıs-Eylül',
    filters: ['budget'],
    image: 'https://images.unsplash.com/photo-1549877452-9c387954fbc2?auto=format&fit=crop&w=1000&q=80',
    imageAlt: 'Budapeşte Parlamento Binası ve Tuna Nehri',
    caption: 'Tuna kıyısı ve Parlamento manzarası',
    highlights: {
      see: ['Macaristan Parlamento Binası', 'Balıkçı Tabyası ve Buda Kalesi', 'Zincirli Köprü'],
      eat: ['Sarımsaklı Lángos', 'Macar gulaşı', 'Kürtőskalács baca keki'],
      do: ['Széchenyi termalleri', 'Szimpla Kert', 'Gece Tuna tekne turu'],
    },
    stays: ['Gece hayatı: Yahudi Mahallesi.', 'Merkez ve alışveriş: Belváros, Peşte yakası.', 'Sakinlik ve manzara: Buda Kale Bölgesi.'],
    transport: ['Liszt Ferenc: 100E ekspres otobüsü Deák Ferenc tér’e gider.', 'Manzaralı rota: 2 numaralı tramvay nehri takip eder.'],
    notes: ['Para birimi forinttir; kur karşılaştırması yapın ve güvenilir ATM kullanın.', 'Széchenyi için terlik ve havlu götürmek işinizi kolaylaştırır.'],
  },
  {
    slug: 'roma',
    name: 'Roma',
    country: 'İtalya',
    coordinates: [41.9028, 12.4964],
    mood: 'Antik pişmiş toprak ve barok',
    summary: 'Antik yapıların arasında yürüyün, Trastevere’de yemek yiyin ve çeşmeleri gece yeniden görün.',
    duration: '4-5 gün',
    budget: 'Orta',
    season: 'Nisan-Mayıs ve ekim',
    filters: ['warm'],
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1000&q=80',
    imageAlt: 'Roma Kolezyumu',
    caption: 'Antik Kolezyum arena çevresi',
    highlights: {
      see: ['Kolezyum ve Roma Forumu', 'Pantheon ve Trevi Çeşmesi', 'Vatikan ve Sistina Şapeli'],
      eat: ['Trastevere’de cacio e pepe', 'Giolitti veya Frigidarium gelato', 'Bonci Pizzarium dilim pizza'],
      do: ['Gece yarısı Trevi Çeşmesi', 'Aventine anahtar deliği', 'Villa Borghese’de bisiklet'],
    },
    stays: ['Otantik akşamlar: Trastevere.', 'Tam merkez: Pantheon ve Navona.', 'Hesaplı ve trene yakın: Monti veya Termini.'],
    transport: ['Fiumicino: Leonardo Express veya havalimanı otobüsüyle Termini’ye geçin.', 'Şehir içi: Merkezde yürümek çoğu rota için pratiktir.'],
    notes: ['Vatikan ve Kolezyum biletlerini resmi kanallardan önceden ayırtın.', 'Masaya oturma ücreti uygulanıp uygulanmadığını sipariş vermeden sorun.'],
  },
  {
    slug: 'paris',
    name: 'Paris',
    country: 'Fransa',
    coordinates: [48.8566, 2.3522],
    mood: 'Gece mavisi ve Fransız zarafeti',
    summary: 'Müzeleri ve Seine kıyısını aynı güne sığdırın, mahalle kafelerinde molayı uzun tutun.',
    duration: '4-5 gün',
    budget: 'Yüksek',
    season: 'Bahar ve sonbahar',
    filters: ['classic'],
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1000&q=80',
    imageAlt: 'Paris’te Eyfel Kulesi',
    caption: 'Eyfel Kulesi ve şehir çatısı',
    highlights: {
      see: ['Louvre ve Musée d’Orsay', 'Eyfel Kulesi ve Şanzelize', 'Sainte-Chapelle vitrayları'],
      eat: ['Sıcak kruvasan', 'L’Entrecôte biftek ve patates', 'Pierre Hermé makaronları'],
      do: ['Montmartre sokak ressamları', 'Seine kıyısı sahafları', 'Le Marais tasarım dükkânları'],
    },
    stays: ['Tarihi ve şık: Le Marais.', 'Bohem: Latin Quarter ve Saint-Germain.', 'Manzaralı: Montmartre.'],
    transport: ['Charles de Gaulle: RER B ile Gare du Nord veya Châtelet yönü.', 'Şehir içi: Navigo Easy veya temassız biniş seçeneklerini kontrol edin.'],
    notes: ['Küçük dükkânlara girerken selam vermek yerel nezaketin parçasıdır.', 'Louvre için alternatif girişlerin güncel erişim durumunu resmi siteden doğrulayın.'],
  },
  {
    slug: 'barselona',
    name: 'Barselona',
    country: 'İspanya',
    coordinates: [41.3874, 2.1686],
    mood: 'Katalan mercanı ve Akdeniz',
    summary: 'Gaudí yapılarından sahile inin, tapas için El Born’a uğrayın ve günü Gràcia’da kapatın.',
    duration: '4 gün',
    budget: 'Orta',
    season: 'Mayıs-Ekim',
    filters: ['warm'],
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1000&q=80',
    imageAlt: 'Barselona’daki Gaudí mimarisi',
    caption: 'Sagrada Família ve Gotik doku',
    highlights: {
      see: ['Sagrada Família', 'Park Güell ve Casa Batlló', 'Gotik Mahalle'],
      eat: ['La Boqueria atıştırmalıkları', 'El Born’da patatas bravas', 'Sahilde deniz ürünlü paella'],
      do: ['Bunkers del Carmel manzarası', 'Barceloneta gün batımı yürüyüşü', 'Gràcia meydanları'],
    },
    stays: ['Tarih ve yaşam: El Born veya Gotik Mahalle.', 'Geniş caddeler: Eixample.', 'Yerel mahalle havası: Gràcia.'],
    transport: ['El Prat: Aerobús ile Catalunya Meydanı.', 'Şehir içi: T-Usual ve T-Casual seçeneklerini yolculuk sayınıza göre karşılaştırın.'],
    notes: ['La Rambla ve metroda telefonunuzu ve cüzdanınızı yakından takip edin.', 'Sagrada Família ve Park Güell biletlerini resmi kanallardan önceden alın.'],
  },
  {
    slug: 'amsterdam',
    name: 'Amsterdam',
    country: 'Hollanda',
    coordinates: [52.3676, 4.9041],
    mood: 'Kanal zümrüdü ve bisiklet kültürü',
    summary: 'Kanallar boyunca yürüyün, müzelere zaman ayırın ve bisiklet şeritlerinde akışı izleyin.',
    duration: '3-4 gün',
    budget: 'Yüksek',
    season: 'Nisan-Mayıs ve yaz',
    filters: ['classic'],
    image: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=1000&q=80',
    imageAlt: 'Amsterdam’ın kanal evleri',
    caption: 'Tarihi kanal evleri ve köprüler',
    highlights: {
      see: ['Rijksmuseum ve Van Gogh Müzesi', 'Anne Frank Evi', 'Vondelpark ve kanallar'],
      eat: ['Sıcak stroopwafel', 'Fabel Friet patatesi', 'Winkel 43 elmalı turtası'],
      do: ['Jordaan’da bisiklet', 'Elektrikli tekne turu', 'NDSM Tersanesi feribotu'],
    },
    stays: ['Manzara ve sakinlik: Jordaan.', 'Genç ve canlı: De Pijp.', 'Merkezi: Dam Meydanı çevresi.'],
    transport: ['Schiphol: Trenle Amsterdam Centraal’a geçin.', 'Şehir içi: Tramvaylarda temassız kartla giriş ve çıkışı okutun.'],
    notes: ['Kırmızı bisiklet yolunda yürümeyin ya da fotoğraf için durmayın.', 'Anne Frank Evi ve Van Gogh Müzesi için biletler erken tükenebilir.'],
  },
];
